addSbtPlugin("org.scalameta"  % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"         % "0.5.2")
addSbtPlugin("com.github.sbt" % "sbt-native-packager"  % "1.10.4")
addSbtPlugin("org.scalameta"  % "sbt-native-image"     % "0.3.4")
addSbtPlugin("com.codecommit" % "sbt-github-actions"   % "0.14.2")
addSbtPlugin("io.shiftleft"   % "sbt-ci-release-early" % "2.0.46")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"        % "0.12.0")
addSbtPlugin("com.github.sbt" % "sbt-dynver"           % "5.0.1")
