addSbtPlugin("org.scalameta"  % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"         % "0.5.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager"  % "1.9.16")
addSbtPlugin("org.scalameta"  % "sbt-native-image"     % "0.3.4")
addSbtPlugin("com.github.sbt" % "sbt-github-actions"   % "0.23.0")
addSbtPlugin("io.shiftleft"   % "sbt-ci-release-early" % "2.0.45")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"        % "0.11.0")
addSbtPlugin("com.dwijnand"   % "sbt-dynver"           % "4.1.1")
