addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.20")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager"  % "1.9.7")
addSbtPlugin("org.scalameta"             % "sbt-native-image"     % "0.3.2")
addSbtPlugin("com.codecommit"            % "sbt-github-actions"   % "0.13.0")
addSbtPlugin("io.shiftleft"              % "sbt-ci-release-early" % "2.0.19")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.10.0")
addSbtPlugin("com.dwijnand"              % "sbt-dynver"           % "4.1.1")
